from __future__ import annotations


SYMBOL_PIPELINE_EVENT_TYPES = frozenset({
    "TOP100_SYMBOL_LOAD",
    "SYMBOL_REGISTERED",
    "CONTRACT_REQUESTED",
    "CONTRACT_RESOLVED",
    "CONTRACT_REQUEST_FAILED",
    "CONTRACT_RESOLVED_FROM_CACHE",
    "MKT_DATA_REQUESTED",
    "MKT_DATA_SUBSCRIBED",
    "FIRST_TICK_RECEIVED",
    "STATE_CREATED",
    "SIGNAL_EVALUATED",
    "SIGNAL_REJECTED",
    "BUY_DECISION",
    "BUY_BLOCKED",
})

SUCCESSFUL_SYMBOL_PIPELINE_EVENTS = frozenset({
    "TOP100_SYMBOL_LOAD",
    "SYMBOL_REGISTERED",
    "CONTRACT_REQUESTED",
    "CONTRACT_RESOLVED",
    "MKT_DATA_REQUESTED",
    "MKT_DATA_SUBSCRIBED",
    "FIRST_TICK_RECEIVED",
    "STATE_CREATED",
    "SIGNAL_EVALUATED",
    "BUY_DECISION",
})
